# deploy/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    env_file: .env.${ENV_MODE}  # Carrega variáveis de ambiente do arquivo .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
