name: Deploy para ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login na AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login no ECR
      run: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin 311141526139.dkr.ecr.us-east-1.amazonaws.com

    - name: Build da imagem
      run: docker build -t fastapi-orm .

    - name: Tag da imagem
      run: docker tag fastapi-orm:latest 311141526139.dkr.ecr.us-east-1.amazonaws.com/fastapi-orm:latest

    - name: Push para o ECR
      run: docker push 311141526139.dkr.ecr.us-east-1.amazonaws.com/fastapi-orm:latest

    - name: Deploy no ECS
      run: |
        aws ecs update-service \
          --cluster fastapi-cluster \
          --service fastapi-td-service \
          --force-new-deployment

    - name: Verificar status do serviço ECS
      run: |
        aws ecs describe-services \
            --cluster fastapi-cluster \
            --services fastapi-td-service